### POST_AUTH

POST {{MAIN_APP_HOST}}/auth HTTP/1.1
Content-Type: application/json
User-Agent: career-page-backend

{
  "session_token": "{{SESSION_TOKEN}}"
}

### POST_NATURAL_LANGUAGE_SEARCH

POST {{JOB_APP_HOST}}/ats/api/v1/career_page/natural_language_search HTTP/1.1
Content-Type: application/json
Jwt-Token: {{POST_AUTH.response.body.$.token}}

{
  "country_code": "AU",
  "natural_input": "Barista"
}

### GET_CAREER_PAGE_JOBS

# @jq { "items": .data.items }
GET {{JOB_APP_HOST}}/ats/api/v2/career_page/jobs?item_per_page=10
  &page_index=1
  &date_posted=90
  &salary_min=0
  &sort=relevance
  &radius=25
  &query=Software Engineer
  &country_code=AU
  &hide_applied_jobs=false HTTP/1.1
Jwt-Token: {{POST_AUTH.response.body.$.token}}

### GET_RECOMMENDED_CAREER_PAGE_JOBS

# @jq { "items": .data.items }
GET {{JOB_APP_HOST}}/ats/api/v1/job_seeker/recommended_jobs/career_page_jobs?item_per_page=10
  &page_index=1
  &date_posted=90
  &days_ago=90
  &salary_min=0
  &sort=relevance
  &radius=25
  &query=Barista
  &country_code=AU
  &hide_applied_jobs=false HTTP/1.1
Jwt-Token: {{POST_AUTH.response.body.$.token}}
