###
@organisationId = 488568
@email = andy.leung+hronlyadmin1@employmenthero.com
@password = employmenthero123

### 0. Login to get cookies
# @name login
POST {{MAIN_APP_HOST}}/users/sign_in
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

user[email]={{email}}&user[password]={{password}}&force_relogin=false


### 1. Get Session Token
# @name getSessionToken
POST {{MAIN_APP_HOST}}/api/v2/sessions
Content-Type: application/json
Accept: application/json

{
  "data": {
    "attributes": {
      "email": "{{email}}",
      "password": "{{password}}",
      "device_id": "simulator"
    }
  }
}

### 2. Get Auth Info (using session token)
# @name getAuthInfo
# @attach-cookie-jar
POST {{MAIN_APP_HOST}}/auth
Accept: application/json
Content-Type: application/json
Session-Token: {{getSessionToken.response.body.$.data.attributes.session_token}}

### Get JWT Token
POST {{MAIN_APP_HOST}}/auth
Content-Type: application/json
User-Agent: career-page-backend

{
  "session_token": "{{getSessionToken.response.body.$.data.attributes.session_token}}"
}

############################
### Mobile login

POST {{MAIN_APP_HOST}}/api/v3/omop/authentication/sign_in
Accept: application/json
Content-Type: application/json

{
  "data": {
    "attributes": {
      "email": "{{email}}",
      "password": "{{password}}",
      "device_id": "simulator"
    }
  }
}
