### 

@atsToken = wDfDKI6L1W2Y2vlM-LDye
@email = toan.nguyen+candidate.1@employmenthero.com
@password = Khoa@10PM


### POST_SESSIONS_CAREER_PAGE

# @jq { "email": .data.attributes.email, "session_token": .data.attributes.session_token }

POST {{MAIN_APP_HOST}}/api/v2/sessions/career-page HTTP/1.1
Content-Type: application/json
X-Ats-Token: {{atsToken}}

{
  "data": {
    "attributes": {
      "device_id": "simulator",
      "device_info": {
        "app_version": "0.0.1",
        "platform": "ios"
      },
      "email": "{{email}}",
      "password": "{{password}}"
    }
  }
}


### POST_AUTH

POST {{MAIN_APP_HOST}}/auth HTTP/1.1
Content-Type: application/json
User-Agent: career-page-backend

{
  "session_token": "85f3d87262d98aa777926302ef11e0e438f5e52f7dbf914873981789959f9abd8fc420ed90ea0e38159123c21c71bda843940da61bac321e283e4bc4d781cf29"
}


### POST_NATURAL_LANGUAGE_SEARCH

POST {{JOB_APP_HOST}}/api/ats/api/v1/career_page/natural_language_search HTTP/1.1
Content-Type: application/json
Jwt-Token: {{POST_AUTH.response.body.$.token}}

{
  "country_code": "AU",
  "natural_input": "Senior Engineer"
}


### GET_CAREER_PAGE_JOBS

GET {{JOB_APP_HOST}}/api/ats/api/v2/career_page/jobs?item_per_page=10&page_index=1&date_posted=90&salary_min=0&sort=relevance&radius=25&query=Devops&country_code=AU&hide_applied_jobs=true HTTP/1.1
Content-Type: application/json
Jwt-Token: {{POST_AUTH.response.body.$.token}}
