### POST_SESSIONS_CAREER_PAGE

# @jq { "email": .data.attributes.email, "session_token": .data.attributes.session_token, "org_id": .data.relationships.organisations.data[0].id, "member_id": .data.relationships.members.data[0].id }
POST {{MAIN_APP_HOST}}/api/v2/sessions/career-page HTTP/1.1
Content-Type: application/json

{
  "data": {
    "attributes": {
      "email": "{{SAP_USERNAME_1}}",
      "password": "{{SAP_PASSWORD_1}}"
    }
  }
}

### POST_AUTH

POST {{MAIN_APP_HOST}}/auth HTTP/1.1
Content-Type: application/json
User-Agent: career-page-backend

{
  "session_token": "{{SAP_USERNAME_1_SESSION_TOKEN}}"
}

### FEATURE FLAG API

GET https://api.ehrocks.com/feature-flag-api/v2/features?page_index=1
  &item_per_page=20
  &exclude_entitlements=true
  &query=eh_work_app_slice_2 HTTP/1.1
Accept: application/json
Content-Type: application/json
Jwt-Token: {{POST_AUTH.response.body.$.token}}
