@organisationId = 148227


### POST_SESSIONS_CAREER_PAGE

# @jq { "email": .data.attributes.email, "session_token": .data.attributes.session_token, "org_id": .data.relationships.organisations.data[0].id, "member_id": .data.relationships.members.data[0].id }
POST {{MAIN_APP_HOST}}/api/v2/sessions/career-page HTTP/1.1
Content-Type: application/json

{
  "data": {
    "attributes": {
      "email": "{{MANAGER_USERNAME_1}}",
      "password": "{{MANAGER_PASSWORD_1}}"
    }
  }
}

### POST_AUTH

POST {{MAIN_APP_HOST}}/auth HTTP/1.1
Content-Type: application/json
User-Agent: career-page-backend

{
  "session_token": "{{MANAGER_USERNAME_1_SESSION_TOKEN}}"
}

### GET_TODO_ITEMS

# @jq { "data": .data }
GET {{MAIN_APP_HOST}}/api/v3/organisations/{{organisationId}}/todo_items/mobile_task_widget?page_index=1 
  &item_per_page=5 
  &features[]=timesheet 
  &features[]=leave 
  &features[]=expense HTTP/1.1
Jwt-Token: {{POST_AUTH.response.body.$.token}}
