@memberId = 374180
@organisationId = 20803


### POST_GET_SESSION_TOKEN

# @jq { "data": .data }
POST {{MAIN_APP_HOST}}/api/v2/sessions HTTP/1.1
Content-Type: application/json

{
  "data": {
    "attributes": {
      "email": "{{MANAGER_USERNAME_1}}",
      "password": "{{MANAGER_PASSWORD_1}}",
      "device_id": "simulator"
    }
  }
}

### POST_AUTH

POST {{MAIN_APP_HOST}}/auth HTTP/1.1
Content-Type: application/json
User-Agent: career-page-backend

{
  "session_token": "{{MANAGER_USERNAME_1_SESSION_TOKEN}}"
}

### POST_TIMESHEET_ENTRIES

# @jq { "id": .data.id, "date": .data.date }
POST {{MAIN_APP_HOST}}/api/v3/organisations/{{organisationId}}/members/{{memberId}}/timesheet_entries HTTP/1.1
Content-Type: application/json
Jwt-Token: {{POST_AUTH.response.body.$.token}}

{
  "timesheet_entry": {
    "breaks_attributes": [
      {
        "end_hm": "1:00 PM",
        "start_hm": "12:00 PM"
      }
    ],
    "comment": "Daily work",
    "date": "03/07/2026",
    "end_hm": "05:00 PM",
    "hr_position_id": "7b614e01-a696-4188-84cf-c589ba786d12",
    "location_id": 42112,
    "member_id": "{{memberId}}",
    "shift_condition_ids": [],
    "start_hm": "08:00 AM",
    "type": "start_and_end_times_timesheet_entry"
  }
}

### GET_TIMESHEET_ENTRIES

# @jq { "total_items": .data.total_items, "items": .data.items, "members": .data.members}
GET {{MAIN_APP_HOST}}/api/v3/organisations/{{organisationId}}/members/{{memberId}}/timesheet_entries?page_index=1
  &item_per_page=5 HTTP/1.1
Jwt-Token: {{POST_AUTH.response.body.$.token}}

### PUT_TIMESHEET_ENTRIES

DELETE {{MAIN_APP_HOST}}/api/v3/organisations/{{organisationId}}/members/{{memberId}}/timesheet_entries/{{12345}} HTTP/1.1
Jwt-Token: {{POST_AUTH.response.body.$.token}}

### POST_EXPENSES

POST https://expenses.staging.ehrocks.com/api/v1/expenses HTTP/1.1
Content-Type: application/json
Jwt-Token: {{POST_AUTH.response.body.$.token}}

{
  "currency": "USD",
  "amount": "500.00",
  "expense_category_id": "a1b2c3d4-5678-90ab-cdef-1234567890ab",
  "location_external_id": "5678",
  "purchase_date": "02/15/2025",
  "supplier": "Sample Supplier",
  "attachments_attributes": [],
  "tax_amount": "10.00",
  "tax_rate": 5,
  "tax_code": null,
  "tax_code_display": null
}

### POST_RECOGNITIONS

POST {{NOMINATION_HOST}}/api/v1/recognitions HTTP/1.1
Content-Type: application/json
Jwt-Token: {{POST_AUTH.response.body.$.token}}

{
  "recognition": {
    "company_value_id": "a618cf71-5738-4f40-afcd-fdf59b595f5b",
    "nominee_id": "e098d071-3ad0-4204-910c-b44b9fc53b0f",
    "message_type": "slate_0.58",
    "message": [
      {
        "type": "paragraph",
        "children": [
          {
            "text": "We recognise that it will take all of us, working together at 100% to achieve our vision. We know that the strongest teams foster diverse personalities, talents and skills and we believe in using our experience to help others achieve their best."
          }
        ]
      }
    ]
  }
}
