@businessId = 49067
@employeeId = 5545065
@status = Submitted


### GET_TIMESHEETS

## @jq [.[] | select(.status == {{status}} and .employeeId == {{employeeId}})]
# @jq [.[] | select(.employeeId == {{employeeId}}) | {id, employeeId, status, startTime, endTime}]
GET {{WORKZONE_HOST}}/api/v2/business/{{businessId}}/timesheet HTTP/1.1
Accept: application/json
Authorization: Basic {{KEYPAY_STAGING_API_KEY}}
Cache-Control: no-store

### CREATE_A_TIMESHEET

POST {{WORKZONE_HOST}}/api/v2/business/{{businessId}}/timesheet HTTP/1.1
Authorization: Basic {{KEYPAY_STAGING_API_KEY}}
Cache-Control: no-store
Content-Type: application/json

{
  "employeeId": "{{employeeId}}",
  "startTime": "2025-12-29T09:00:00",
  "endTime": "2025-12-29T18:00:00",
  "workTypeId": "97627",
  "locationId": "190704",
  "breaks": [
    {
      "startTime": "2025-12-29T11:45:00",
      "endTime": "2025-12-29T12:45:00",
      "isPaidBreak": false
    }
  ],
  "shiftConditionIds": ["97628"]
}

### DELETE_A_TIMESHEET

DELETE {{WORKZONE_HOST}}/api/v2/business/{{businessId}}/timesheet/233140623 HTTP/1.1
Accept: application/json
Authorization: Basic {{KEYPAY_STAGING_API_KEY}}
Cache-Control: no-store
