export MY_GITHUB_USERNAME="phuongthuan"

export ZSH="$HOME/.oh-my-zsh"

# DOTFILES folder
export DOTFILES="~/.dotfiles"

# nvim env
export EDITOR="nvim"
export NVIM_CONFIG_DIR="~/.config/nvim"
export NVIM_USE_TSSERVER=false
export NVIM_USE_VTSLS=true
export LAZYVIM_CONFIG="~/.config/lazyvim/init.lua"
export LAZYVIM_CONFIG_DIR="~/.config/lazyvim"

# iCloud Drive
export ICLOUD_DRIVE="~/Library/Mobile Documents/com~apple~CloudDocs"
export ICLOUD_DRIVE_OBSIDIAN_DIR="~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Notes"

# go
# export GO_ROOT="/usr/local/go/bin"
# export PATH="$GO_ROOT:/usr/local/sbin:$PATH"

export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools

# Export path for EH herocli
export PATH=$PATH:$HOME/.local/bin

# java jdk
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home

. "$HOME/.cargo/env"
