# ~/.zshrc

export ZSH="$HOME/.oh-my-zsh"

# DOTFILES folder
export DOTFILES=~/Programming/dotfiles

# Enable vim mode
bindkey -v

# https://github.com/ergenekonyigit/lambda-gitster
ZSH_THEME="lambda-gitster"

plugins=(
  git
  vi-mode
  zsh-autosuggestions
  zsh-syntax-highlighting
  colorize
  dotenv
)

# Lazyload rbenv
# export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# https://github.com/wting/autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

export EDITOR="nvim"
export PATH="/usr/local/sbin:$PATH"

export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools

# Load seperated config files
for conf in "$HOME/.config/zsh/"*.zsh; do
  source "${conf}"
done
unset conf

# Lazyload nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                    # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

source $ZSH/oh-my-zsh.sh

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
