# ~/.zshrc

export ZSH="$HOME/.oh-my-zsh"

# Default Editor
export EDITOR="nvim"

# Theme
ZSH_THEME="lambda-gitster"

# Plugins
plugins=(git zsh-autosuggestions zsh-syntax-highlighting colorize)

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# Load seperated config files
for conf in "$HOME/.config/zsh/"*.zsh; do
  source "${conf}"
done
unset conf

# Load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

source $ZSH/oh-my-zsh.sh

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Enable vim mode
bindkey -v
