# ~/.zshrc

# enable vim mode
bindkey -v

# ZSH_THEME="refined"
plugins=(
  git
  vi-mode
  zsh-autosuggestions
  # zsh-syntax-highlighting
)

# oh-my-zsh
source $ZSH/oh-my-zsh.sh

# starship
eval "$(starship init zsh)"
export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml

# zoxide
eval "$(zoxide init zsh)"

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --zsh)"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# load seperated config files
for conf in "$HOME/.config/zsh/"*.zsh; do
  source "${conf}"
done
unset conf

# asdf
. /opt/homebrew/opt/asdf/libexec/asdf.sh

export GPG_TTY=$(tty)
